In [1]:
cd ..

/home/is/akiyoshi-n/my-project


In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
import time
from datetime import datetime
import torch
import torch.nn as nn
from torch import cuda
from src.my_project.dataset import load_multiclass_dataset, load_and_merge_labels
from src.my_project.train import MultiClassActClassifier
from src.my_project.utils import count_unique_elements
from transformers import BertTokenizer, BertJapaneseTokenizer
from transformers import AutoTokenizer, AutoModelForMaskedLM
import pickle

In [3]:
DATASET_PATH = Path('/home/is/akiyoshi-n/my-project/data')
output_dir = Path('/home/is/akiyoshi-n/my-project/outputs')
# パラメータの設定
MAX_LEN = 128
# DROP_RATE = 0.4
BATCH_SIZE = 16
NUM_EPOCHS = 100
LEARNING_RATE = 2e-5
num_folds = 5
PATIENCE = 5
SEED = 2023

# デバイスの指定
device = "cuda:1" if cuda.is_available() else "cpu"

timestamp = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")

In [4]:
# データの読み込み
data, class_name = load_multiclass_dataset(f"{DATASET_PATH}/act_classification_final.xlsx")

/home/is/akiyoshi-n/my-project/.venv/lib/python3.11/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)


### ラベリング

In [5]:
# 事前学習済みモデル（BERT）の指定
MODEL_NAME = 'bert-base-uncased'
tokenizer = BertTokenizer.from_pretrained(MODEL_NAME)

# 交差検証の実行
trainer = MultiClassActClassifier(tokenizer=tokenizer,model_name = MODEL_NAME, device=device, seed=SEED)
fold_scores, fold_f1, fold_hamming, best_model = trainer.cross_validation(MODEL_NAME, data, num_folds, NUM_EPOCHS,
                                                            device, LEARNING_RATE,
                                                            BATCH_SIZE, output_dir,
                                                            MAX_LEN, timestamp)

-----------------Fold: 1-----------------


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


KeyboardInterrupt: 

In [ ]:
# 東北大BERT-v2
MODEL_NAME = 'cl-tohoku/bert-base-japanese-v2'
tokenizer = BertJapaneseTokenizer.from_pretrained(MODEL_NAME)

trainer = MultiClassActClassifier(tokenizer=tokenizer, model_name = MODEL_NAME, device=device, seed=SEED)
fold_scores, fold_f1, fold_hamming, best_model = trainer.cross_validation(MODEL_NAME, data, num_folds, NUM_EPOCHS,
                                                            device, LEARNING_RATE,
                                                            BATCH_SIZE, output_dir, MAX_LEN, timestamp)

-----------------Fold: 1-----------------


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at cl-tohoku/bert-base-japanese-v2 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Early stopping. No improvement in loss.
Accuracy: 0.4909090909090909
macro f1: 0.14244288397387378
humming: 0.04045454545454545
-----------------Fold: 2-----------------


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at cl-tohoku/bert-base-japanese-v2 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Early stopping. No improvement in loss.
Accuracy: 0.509090909090909
macro f1: 0.21029498525073748
humming: 0.042045454545454546
-----------------Fold: 3-----------------


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at cl-tohoku/bert-base-japanese-v2 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Early stopping. No improvement in loss.
Accuracy: 0.5045454545454545
macro f1: 0.13232243848948655
humming: 0.04045454545454545
-----------------Fold: 4-----------------


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at cl-tohoku/bert-base-japanese-v2 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Early stopping. No improvement in loss.
Accuracy: 0.55
macro f1: 0.20891157776303312
humming: 0.04090909090909091
-----------------Fold: 5-----------------


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at cl-tohoku/bert-base-japanese-v2 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Early stopping. No improvement in loss.
Accuracy: 0.5
macro f1: 0.26536577226004543
humming: 0.038863636363636364
-------------------------------------
finished epochs : [38, 92, 42, 78, 84]
Average Accuracy: 0.510909090909091
Average macro f1: 0.19186753154743527
Average humming: 0.04054545454545454


In [5]:
# 東北大BERT-v3
MODEL_NAME = 'cl-tohoku/bert-base-japanese-v3'
tokenizer = BertJapaneseTokenizer.from_pretrained(MODEL_NAME)

# 交差検証の実行
trainer = MultiClassActClassifier(tokenizer=tokenizer, model_name = MODEL_NAME, device=device, seed=SEED)
fold_scores, fold_f1, fold_hamming, best_model, all_predictions, all_labels = trainer.cross_validation(MODEL_NAME, data, num_folds, NUM_EPOCHS,
                                                            device, LEARNING_RATE,
                                                            BATCH_SIZE, output_dir, MAX_LEN, timestamp, num_labels=20)


-----------------Fold: 1-----------------


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at cl-tohoku/bert-base-japanese-v3 and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Early stopping. No improvement in loss.
Accuracy: 0.5318181818181819
macro f1: 0.1870736586068394
humming: 0.042954545454545454
-----------------Fold: 2-----------------


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at cl-tohoku/bert-base-japanese-v3 and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Early stopping. No improvement in loss.
Accuracy: 0.4909090909090909
macro f1: 0.21708908635224425
humming: 0.0425
-----------------Fold: 3-----------------


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at cl-tohoku/bert-base-japanese-v3 and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Early stopping. No improvement in loss.
Accuracy: 0.5545454545454546
macro f1: 0.17884219292637424
humming: 0.038863636363636364
-----------------Fold: 4-----------------


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at cl-tohoku/bert-base-japanese-v3 and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Early stopping. No improvement in loss.
Accuracy: 0.5454545454545454
macro f1: 0.17087259473279018
humming: 0.03772727272727273
-----------------Fold: 5-----------------


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at cl-tohoku/bert-base-japanese-v3 and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Early stopping. No improvement in loss.
Accuracy: 0.4818181818181818
macro f1: 0.2277756183236878
humming: 0.042954545454545454
-------------------------------------
finished epochs : [89, 36, 90, 43, 29]
Average Accuracy: 0.5209090909090909
Average macro f1: 0.1963306301883872
Average humming: 0.041


In [12]:
"""
# リスト保存
with open("all_predictions.pkl", "wb") as file:
    pickle.dump(all_predictions, file)
with open("all_labels.pkl", "wb") as file:
    pickle.dump(all_labels, file)
"""
# 保存したリストを使用
with open("all_predictions.pkl", "rb") as file:
    all_predictions = pickle.load(file)
    all_predictions = np.array(all_predictions)
with open("all_labels.pkl", "rb") as file:
    all_labels = pickle.load(file)
    all_labels = np.array(all_labels)

In [15]:
print(all_predictions.shape)
print(type(all_predictions))
print(all_predictions[0])
print(all_labels[2])

(1100, 20)
<class 'numpy.ndarray'>
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]


In [7]:
class_name

array(['1 - A. 睡眠', '1 - B. 身の回りの用事', '1 - C - a. 食事-飲酒あり',
       '1 - C - b. 食事-飲酒なし・不明', '2 - A - a. 通勤・通学', '2 - A - b. その他の移動',
       '2 - B. 仕事', '2 - C. 学業', '2 - D. 家事', '2 - F. 育児',
       '3 - A. メディア（テレビ・ラジオ・新聞・雑誌・ネット）', '3 - B. 買い物',
       '3 - C - a. 趣味・娯楽-体動かす', '3 - C - b. 趣味・娯楽-体動かさない',
       '3 - D - a. 交際-物理的接触', '3 - D - b. 交際-オンライン的接触', '3 - E. 受診・療養',
       '3 - F - a. 喫煙', '3 - F - b. その他の活動(事故など)', '4. 活動なし'],
      dtype=object)

In [17]:
from sklearn.metrics import accuracy_score, f1_score, hamming_loss
accuracy = accuracy_score(all_labels, all_predictions)
f1 = f1_score(all_labels, all_predictions, average='macro', zero_division=0)  # マクロ平均F1スコアの計算
hamming = hamming_loss(all_labels, all_predictions)  # ハムミング損失の計算
print(accuracy)
print(f1)
print(hamming)

0.5209090909090909
0.20489927444563763
0.041


In [19]:
from sklearn.metrics import confusion_matrix, multilabel_confusion_matrix

# 混合行列を計算
cm = multilabel_confusion_matrix(all_labels, all_predictions)

# 混合行列を表示
for i, matrix in enumerate(cm):
    print(f"Label {class_name[i]}:")
    print(matrix)
    print("-" * 20)


Label 1 - A. 睡眠:
[[1074    5]
 [  13    8]]
--------------------
Label 1 - B. 身の回りの用事:
[[1087    1]
 [  12    0]]
--------------------
Label 1 - C - a. 食事-飲酒あり:
[[1076    6]
 [  16    2]]
--------------------
Label 1 - C - b. 食事-飲酒なし・不明:
[[1046    8]
 [  31   15]]
--------------------
Label 2 - A - a. 通勤・通学:
[[1097    0]
 [   3    0]]
--------------------
Label 2 - A - b. その他の移動:
[[1028   16]
 [  39   17]]
--------------------
Label 2 - B. 仕事:
[[1076    2]
 [  18    4]]
--------------------
Label 2 - C. 学業:
[[1099    0]
 [   1    0]]
--------------------
Label 2 - D. 家事:
[[1084    4]
 [  11    1]]
--------------------
Label 2 - F. 育児:
[[1096    0]
 [   4    0]]
--------------------
Label 3 - A. メディア（テレビ・ラジオ・新聞・雑誌・ネット）:
[[898  64]
 [ 97  41]]
--------------------
Label 3 - B. 買い物:
[[1059   13]
 [  24    4]]
--------------------
Label 3 - C - a. 趣味・娯楽-体動かす:
[[1078    4]
 [  14    4]]
--------------------
Label 3 - C - b. 趣味・娯楽-体動かさない:
[[1000   19]
 [  61   20]]
--------------------
Label

In [ ]:
best_model

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(32768, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12,

In [ ]:
from src.my_project.dataset import preprocess_multiclass_dataset, load_multiclass_dataset
from transformers import BertTokenizer, BertJapaneseTokenizer, BertForSequenceClassification
from pathlib import Path
from torch.utils.data import DataLoader
from torch import cuda
import torch
from sklearn.metrics import accuracy_score, f1_score, hamming_loss
# デバイスの指定
device = "cuda:1" if cuda.is_available() else "cpu"

In [ ]:
# データの読み込み
data = load_multiclass_dataset(f"{DATASET_PATH}/act_classification_final.xlsx")
data = preprocess_multiclass_dataset(data, tokenizer, 128)
train_dataloader = DataLoader(data, 16)
best_model.eval()
total_predictions = []
total_labels = []

# 予測
with torch.no_grad():
    for input_ids, attention_mask, labels in train_dataloader:
        input_ids = input_ids.to(device)
        attention_mask = attention_mask.to(device)
        labels = labels.to(device)

        outputs = best_model(input_ids, attention_mask)
        predictions = torch.sigmoid(outputs.logits)  # シグモイド活性化関数の適用
        predictions = (predictions > 0.5).float()  # 0.5を閾値として二値化

        total_predictions.extend(predictions.detach().cpu().numpy())
        total_labels.extend(labels.detach().cpu().numpy())

/home/is/akiyoshi-n/my-project/.venv/lib/python3.11/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)


In [ ]:
total_predictions

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1.], dtype=float32),
 array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1.], dtype=float32),
 array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1.],

In [ ]:
total_labels

[array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 0, 

In [ ]:
data = preprocess_multiclass_dataset(data, tokenizer, 128)
train_dataloader = DataLoader(data, 16)
best_model.to(device)
best_model.eval()
total_predictions = []
total_labels = []
for input_ids, attention_mask, labels in train_dataloader:
    input_ids = input_ids.to(device)
    attention_mask = attention_mask.to(device)
    labels = labels.to(device)
    outputs = best_model(input_ids, attention_mask)
    predictions = torch.sigmoid(outputs.logits)  # シグモイド活性化関数の適用
    predictions = (predictions > 0.5).float()  # 0.5を閾値として二値化

IndexError: too many indices for tensor of dimension 2

In [ ]:
data

In [ ]:
data

{'texts': ['あたしのダイスキな姉御のパパは85歳で現役歯科医。そのパパが去年突然倒れた。胃癌。手術もして一度は仕事復帰。しかし。今日、再手術が。無事済んでＩＣＵ。頑張って！癌と闘う全ての人に安らぎを神様おねがいします☆',
  'テストしに歩いてたら１、２年生対象のアンケートしてるんですか…って言われたのだがすみません見た目若くて…と返してしまった嫌味みたい！\u3000童顔ってこと',
  '教授最高だった。何度も言うが、1996が大好きだ！生美貌の青空(と思い込んでる曲)と千のナイフ(と思い込んでる曲)に感動した。',
  '「ありがとう」「嬉しい」というような言葉は、かけられた側にもその気持ちが伝播する。感謝の心は、人間関係を円滑に保つ最大の潤滑油だろう。感謝の心は常日頃忘れないようにしたい。改めて、強くそう思う。',
  'さて、お家帰ってご飯にしよう。今夜は焼肉。昼間届いた豚肉で焼肉。備蓄してある肉が大量にあるから、明後日まで三日連続焼肉して、明明後日からは鍋にして三日ほど続け、それからまた焼肉という、肉々しい日々を過ごすことも可能……毎日、ちゃんとお家帰って食事が出来れば（ﾉ∀｀）',
  '今日は砂川→新青梅街道→R16二本木→飯能阿須→飯能駅→東飯能駅→小曾木街道→青梅市民会館前→新青梅街道→イオンモールむさし村山ミュー→砂川とクルマを動かしてきました。クルマの運転はそれはもう楽しいです！',
  'うちのおかぁちゃんは旧姓澤田なんやけど昔家に『沢田研二さんのお宅ですか？』って電話があったそうな\u3000たまたまそこに居合わせたうちのおとぉちゃんが『研二はいま外出しております』っていったからもう大変ｗ\u3000いくら京都出身やからって沢田に片っ端からかけてたんすかね？',
  'リプライ送って帰ってこないときの大体の例\u3000\u3000①自分の発言が流された\u3000②たまたま離籍した\u3000③返事しにくい\u3000④返しにくい\u3000⑤返信が思いつかなかった\u3000⑥一応ふぁぼった ヮ＜',
  'こんな時でも\u3000ＪＡＬは安全性・定時性・快適性を貫くべく\u3000現場は全力で頑張ってほしい！現場の力が今こそ問われる。それが企業の底力だ！！',
  '忘れたい恥ずかしい過去を黒歴史と言うが、今言ったりや

In [ ]:
MODEL_NAME = "nlp-waseda/roberta-base-japanese"
tokenizer = AutoModelForMaskedLM.from_pretrained(MODEL_NAME)

# 交差検証の実行
trainer = MultiClassActClassifier(tokenizer=tokenizer, model_name = MODEL_NAME, criterion=CRITERION, device=device, seed=SEED)
fold_scores, fold_f1, fold_hamming, best_model = trainer.cross_validation(MODEL_NAME, data, num_folds, NUM_EPOCHS,
                                                            device, LEARNING_RATE,
                                                            BATCH_SIZE, output_dir, MAX_LEN, timestamp)


### データのマージ

In [9]:
merge_dict = {'2 - D. 家事': '1 - B. 身の回りの用事', '2 - F. 育児': '1 - B. 身の回りの用事', '2 - C. 学業': '2 - B. 仕事', }
data, class_name = load_and_merge_labels(f"{DATASET_PATH}/act_classification_final.xlsx", merge_labels=merge_dict)
print(class_name)

['1 - A. 睡眠' '1 - B. 身の回りの用事' '1 - C - a. 食事-飲酒あり' '1 - C - b. 食事-飲酒なし・不明'
 '2 - A - a. 通勤・通学' '2 - A - b. その他の移動' '2 - B. 仕事'
 '3 - A. メディア（テレビ・ラジオ・新聞・雑誌・ネット）' '3 - B. 買い物' '3 - C - a. 趣味・娯楽-体動かす'
 '3 - C - b. 趣味・娯楽-体動かさない' '3 - D - a. 交際-物理的接触' '3 - D - b. 交際-オンライン的接触'
 '3 - E. 受診・療養' '3 - F - a. 喫煙' '3 - F - b. その他の活動(事故など)' '4. 活動なし']


/home/is/akiyoshi-n/my-project/.venv/lib/python3.11/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)


In [10]:
print(len(dataset['labels'][0]))
dataset['labels'][0:5]

17


[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [11]:
# 東北大BERT-v3
MODEL_NAME = 'cl-tohoku/bert-base-japanese-v3'
tokenizer = BertJapaneseTokenizer.from_pretrained(MODEL_NAME)

# 交差検証の実行
trainer = MultiClassActClassifier(tokenizer=tokenizer, model_name = MODEL_NAME, device=device, seed=SEED)
fold_scores, fold_f1, fold_hamming, best_model, all_predictions, all_labels = trainer.cross_validation(MODEL_NAME, data, num_folds, NUM_EPOCHS,
                                                            device, LEARNING_RATE,
                                                            BATCH_SIZE, output_dir, MAX_LEN, timestamp, num_labels=17)


-----------------Fold: 1-----------------


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at cl-tohoku/bert-base-japanese-v3 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Early stopping. No improvement in loss.
Accuracy: 0.5772727272727273
macro f1: 0.27996215337525016
humming: 0.04224598930481283
-----------------Fold: 2-----------------


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at cl-tohoku/bert-base-japanese-v3 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Early stopping. No improvement in loss.
Accuracy: 0.4772727272727273
macro f1: 0.2291804571089062
humming: 0.051336898395721926
-----------------Fold: 3-----------------


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at cl-tohoku/bert-base-japanese-v3 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Early stopping. No improvement in loss.
Accuracy: 0.5181818181818182
macro f1: 0.2929923305249467
humming: 0.04759358288770053
-----------------Fold: 4-----------------


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at cl-tohoku/bert-base-japanese-v3 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Early stopping. No improvement in loss.
Accuracy: 0.5045454545454545
macro f1: 0.29911631131075267
humming: 0.04411764705882353
-----------------Fold: 5-----------------


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at cl-tohoku/bert-base-japanese-v3 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Early stopping. No improvement in loss.
Accuracy: 0.5318181818181819
macro f1: 0.21877559856538087
humming: 0.04866310160427807
-------------------------------------
finished epochs : [77, 24, 85, 36, 78]
Average Accuracy: 0.5218181818181817
Average macro f1: 0.2640053701770473
Average humming: 0.04679144385026738


In [12]:
from sklearn.metrics import confusion_matrix, multilabel_confusion_matrix

# 混合行列を計算
cm = multilabel_confusion_matrix(all_labels, all_predictions)

# 混合行列を表示
for i, matrix in enumerate(cm):
    print(f"Label {class_name[i]}:")
    print(matrix)
    print("-" * 20)

Label 1 - A. 睡眠:
[[1076    3]
 [  15    6]]
--------------------
Label 1 - B. 身の回りの用事:
[[1063   10]
 [  24    3]]
--------------------
Label 1 - C - a. 食事-飲酒あり:
[[1077    5]
 [  14    4]]
--------------------
Label 1 - C - b. 食事-飲酒なし・不明:
[[1040   14]
 [  29   17]]
--------------------
Label 2 - A - a. 通勤・通学:
[[1097    0]
 [   3    0]]
--------------------
Label 2 - A - b. その他の移動:
[[1030   14]
 [  38   18]]
--------------------
Label 2 - B. 仕事:
[[1073    4]
 [  14    9]]
--------------------
Label 3 - A. メディア（テレビ・ラジオ・新聞・雑誌・ネット）:
[[938  24]
 [115  23]]
--------------------
Label 3 - B. 買い物:
[[1062   10]
 [  21    7]]
--------------------
Label 3 - C - a. 趣味・娯楽-体動かす:
[[1080    2]
 [  12    6]]
--------------------
Label 3 - C - b. 趣味・娯楽-体動かさない:
[[1004   15]
 [  60   21]]
--------------------
Label 3 - D - a. 交際-物理的接触:
[[1087    2]
 [  11    0]]
--------------------
Label 3 - D - b. 交際-オンライン的接触:
[[1004   42]
 [  29   25]]
--------------------
Label 3 - E. 受診・療養:
[[1094    1]
 [   5    0]]
