In [1]:
import torch

### サーバーで利用できるGPUについて

In [2]:
# 利用可能なGPUの数を確認
if torch.cuda.is_available():
    print(f'利用可能なGPUの数: {torch.cuda.device_count()}')
    
    # 各GPUの名前を表示
    for i in range(torch.cuda.device_count()):
        print(f'GPU {i}: {torch.cuda.get_device_name(i)}')
else:
    print('利用可能なGPUはありません')

利用可能なGPUの数: 3
GPU 0: Quadro RTX 8000
GPU 1: Quadro RTX 8000
GPU 2: Quadro P6000


Quadro RTX 8000
1. CUDAコア: 4608 CUDAコア
2. メモリ: 48GBのGDDR6メモリ
3. レイトレーシング: RTコアを搭載しており、リアルタイムレイトレーシングとAI機能をサポート
4. テンソルコア: AIとディープラーニング計算の高速化のためのテンソルコアを搭載

Quadro P6000
1. CUDAコア: 3840 CUDAコア
2. メモリ: 24GBのGDDR5Xメモリ
3. レイトレーシング: RTコアは搭載されていない
4. テンソルコア: テンソルコアは搭載されていない

### テンソルについて

PyTorchテンソルはPyTorchライブラリの基本的なデータ構造<br>
テンソルはニューラルネットワークの入力データ，出力データ，モデルのパラメータなどを表現できる．<br>
<br>
特性
1. 多次元配列
2. GPU対応: GPU上での計算をサポートしている．計算が高速化され，ディープラーニングモデルのトレーニング時間の短縮
3. 自動微分: 計算グラフと勾配計算のサポート．バックプロパゲーションと最適化のプロセスが容易に
4. 操作と変換: スライシング，形状変更，結合など，多くの操作と変換が可能
5. Numpy変換が簡単

In [8]:
# テンソルの作成
x = torch.tensor([[1, 2], [3, 4]])
print(x)

# テンソルの形状の取得
print(x.size())

# テンソルの要素のデータ型の取得
print(x.dtype)

# GPUにテンソルを移動（GPUが利用可能な場合）
if torch.cuda.is_available():
    x = x.to('cuda')
    print(x)
# CPUメモリに戻る
x = x.cpu()
print(x)
numpy_array = x.numpy()
print(numpy_array)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
torch.int64
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]
